from basic_array import Array
my_array = Array()
my_array.push(40)
my_array.push(26)
my_array.push(80)
my_array.push(52)
print(my_array.get_elements())
pop_value = my_array.pop()
print(f"Popped Value : {pop_value}.")
search_value = int(input("Enter an Search Value : "))
search = my_array.search(search_value)
print(f"The value is present in the Array at the index position of : {search}.")
index_value = int(input("Enter an Value for an Index position : "))
index = my_array.index(index_value)
print(f"Index Position : {index}.")
my_array.sort(ascending = False)
sort_values = my_array.get_elements()
print(f"sorted Array : {sort_values}.")
